name: chakre_pdf_viewer
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 1.0.2
homepage: https://github.com/UmeshChakre/pdf_viewer

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cache_manager: ^3.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.0.15

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
