name: advance_pdf_viewer_fork
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 2.0.0
homepage: https://github.com/UmeshChakre/pdf_viewer

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cache_manager: ^3.3.0
  numberpicker: ^2.1.2
  path_provider: ^2.0.15

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
